/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CalendarEvent {
  'id' : Id,
  'title' : string,
  'date' : Date,
  'description' : string,
  'eventType' : string,
}
export type Date = string;
export interface Habit {
  'id' : Id,
  'completionDates' : Array<Date>,
  'name' : string,
}
export type Id = bigint;
export interface ProductivityLog { 'notes' : string, 'rating' : bigint }
export interface RevisionTopic {
  'id' : Id,
  'title' : string,
  'completedIntervals' : Array<bigint>,
  'intervals' : Array<bigint>,
  'createdAt' : bigint,
}
export interface _SERVICE {
  'completeHabit' : ActorMethod<[Id, Date], undefined>,
  'completeRevisionInterval' : ActorMethod<[Id, bigint], undefined>,
  'createCalendarEvent' : ActorMethod<[string, Date, string, string], Id>,
  'createHabit' : ActorMethod<[string], Id>,
  'createRevisionTopic' : ActorMethod<[string, Array<bigint>], Id>,
  'deleteCalendarEvent' : ActorMethod<[Id], undefined>,
  'deleteHabit' : ActorMethod<[Id], undefined>,
  'deleteRevisionTopic' : ActorMethod<[Id], undefined>,
  'getAllCalendarEvents' : ActorMethod<[], Array<CalendarEvent>>,
  'getAllHabits' : ActorMethod<[], Array<Habit>>,
  'getAllProductivityLogs' : ActorMethod<[], Array<[Date, ProductivityLog]>>,
  'getAllRevisionTopics' : ActorMethod<[], Array<RevisionTopic>>,
  'getCalendarEvent' : ActorMethod<[Id], CalendarEvent>,
  'getHabitCompletionDates' : ActorMethod<[Id], Array<Date>>,
  'getProductivityLog' : ActorMethod<[Date], ProductivityLog>,
  'saveProductivityLog' : ActorMethod<[Date, bigint, string], undefined>,
  'updateCalendarEvent' : ActorMethod<
    [Id, string, Date, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];