/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Id = IDL.Nat;
export const Date = IDL.Text;
export const CalendarEvent = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'date' : Date,
  'description' : IDL.Text,
  'eventType' : IDL.Text,
});
export const Habit = IDL.Record({
  'id' : Id,
  'completionDates' : IDL.Vec(Date),
  'name' : IDL.Text,
});
export const ProductivityLog = IDL.Record({
  'notes' : IDL.Text,
  'rating' : IDL.Nat,
});
export const RevisionTopic = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'completedIntervals' : IDL.Vec(IDL.Nat),
  'intervals' : IDL.Vec(IDL.Nat),
  'createdAt' : IDL.Int,
});

export const idlService = IDL.Service({
  'completeHabit' : IDL.Func([Id, Date], [], []),
  'completeRevisionInterval' : IDL.Func([Id, IDL.Nat], [], []),
  'createCalendarEvent' : IDL.Func(
      [IDL.Text, Date, IDL.Text, IDL.Text],
      [Id],
      [],
    ),
  'createHabit' : IDL.Func([IDL.Text], [Id], []),
  'createRevisionTopic' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat)], [Id], []),
  'deleteCalendarEvent' : IDL.Func([Id], [], []),
  'deleteHabit' : IDL.Func([Id], [], []),
  'deleteRevisionTopic' : IDL.Func([Id], [], []),
  'getAllCalendarEvents' : IDL.Func([], [IDL.Vec(CalendarEvent)], ['query']),
  'getAllHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
  'getAllProductivityLogs' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Date, ProductivityLog))],
      ['query'],
    ),
  'getAllRevisionTopics' : IDL.Func([], [IDL.Vec(RevisionTopic)], ['query']),
  'getCalendarEvent' : IDL.Func([Id], [CalendarEvent], ['query']),
  'getHabitCompletionDates' : IDL.Func([Id], [IDL.Vec(Date)], ['query']),
  'getProductivityLog' : IDL.Func([Date], [ProductivityLog], ['query']),
  'saveProductivityLog' : IDL.Func([Date, IDL.Nat, IDL.Text], [], []),
  'updateCalendarEvent' : IDL.Func(
      [Id, IDL.Text, Date, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Id = IDL.Nat;
  const Date = IDL.Text;
  const CalendarEvent = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'date' : Date,
    'description' : IDL.Text,
    'eventType' : IDL.Text,
  });
  const Habit = IDL.Record({
    'id' : Id,
    'completionDates' : IDL.Vec(Date),
    'name' : IDL.Text,
  });
  const ProductivityLog = IDL.Record({
    'notes' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const RevisionTopic = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'completedIntervals' : IDL.Vec(IDL.Nat),
    'intervals' : IDL.Vec(IDL.Nat),
    'createdAt' : IDL.Int,
  });
  
  return IDL.Service({
    'completeHabit' : IDL.Func([Id, Date], [], []),
    'completeRevisionInterval' : IDL.Func([Id, IDL.Nat], [], []),
    'createCalendarEvent' : IDL.Func(
        [IDL.Text, Date, IDL.Text, IDL.Text],
        [Id],
        [],
      ),
    'createHabit' : IDL.Func([IDL.Text], [Id], []),
    'createRevisionTopic' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat)], [Id], []),
    'deleteCalendarEvent' : IDL.Func([Id], [], []),
    'deleteHabit' : IDL.Func([Id], [], []),
    'deleteRevisionTopic' : IDL.Func([Id], [], []),
    'getAllCalendarEvents' : IDL.Func([], [IDL.Vec(CalendarEvent)], ['query']),
    'getAllHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
    'getAllProductivityLogs' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Date, ProductivityLog))],
        ['query'],
      ),
    'getAllRevisionTopics' : IDL.Func([], [IDL.Vec(RevisionTopic)], ['query']),
    'getCalendarEvent' : IDL.Func([Id], [CalendarEvent], ['query']),
    'getHabitCompletionDates' : IDL.Func([Id], [IDL.Vec(Date)], ['query']),
    'getProductivityLog' : IDL.Func([Date], [ProductivityLog], ['query']),
    'saveProductivityLog' : IDL.Func([Date, IDL.Nat, IDL.Text], [], []),
    'updateCalendarEvent' : IDL.Func(
        [Id, IDL.Text, Date, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };