/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProductivityLog {
    notes: string;
    rating: bigint;
}
export interface Habit {
    id: Id;
    completionDates: Array<Date_>;
    name: string;
}
export type Date_ = string;
export interface CalendarEvent {
    id: Id;
    title: string;
    date: Date_;
    description: string;
    eventType: string;
}
export interface RevisionTopic {
    id: Id;
    title: string;
    completedIntervals: Array<bigint>;
    intervals: Array<bigint>;
    createdAt: bigint;
}
export type Id = bigint;
export interface backendInterface {
    completeHabit(id: Id, date: Date_): Promise<void>;
    completeRevisionInterval(id: Id, interval: bigint): Promise<void>;
    createCalendarEvent(title: string, date: Date_, eventType: string, description: string): Promise<Id>;
    createHabit(name: string): Promise<Id>;
    createRevisionTopic(title: string, intervals: Array<bigint>): Promise<Id>;
    deleteCalendarEvent(id: Id): Promise<void>;
    deleteHabit(id: Id): Promise<void>;
    deleteRevisionTopic(id: Id): Promise<void>;
    getAllCalendarEvents(): Promise<Array<CalendarEvent>>;
    getAllHabits(): Promise<Array<Habit>>;
    getAllProductivityLogs(): Promise<Array<[Date_, ProductivityLog]>>;
    getAllRevisionTopics(): Promise<Array<RevisionTopic>>;
    getCalendarEvent(id: Id): Promise<CalendarEvent>;
    getHabitCompletionDates(id: Id): Promise<Array<Date_>>;
    getProductivityLog(date: Date_): Promise<ProductivityLog>;
    saveProductivityLog(date: Date_, rating: bigint, notes: string): Promise<void>;
    updateCalendarEvent(id: Id, title: string, date: Date_, eventType: string, description: string): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async completeHabit(arg0: Id, arg1: Date_): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeHabit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeHabit(arg0, arg1);
            return result;
        }
    }
    async completeRevisionInterval(arg0: Id, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeRevisionInterval(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeRevisionInterval(arg0, arg1);
            return result;
        }
    }
    async createCalendarEvent(arg0: string, arg1: Date_, arg2: string, arg3: string): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createCalendarEvent(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCalendarEvent(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createHabit(arg0: string): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createHabit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHabit(arg0);
            return result;
        }
    }
    async createRevisionTopic(arg0: string, arg1: Array<bigint>): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createRevisionTopic(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRevisionTopic(arg0, arg1);
            return result;
        }
    }
    async deleteCalendarEvent(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCalendarEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCalendarEvent(arg0);
            return result;
        }
    }
    async deleteHabit(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHabit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHabit(arg0);
            return result;
        }
    }
    async deleteRevisionTopic(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRevisionTopic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRevisionTopic(arg0);
            return result;
        }
    }
    async getAllCalendarEvents(): Promise<Array<CalendarEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCalendarEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCalendarEvents();
            return result;
        }
    }
    async getAllHabits(): Promise<Array<Habit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHabits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHabits();
            return result;
        }
    }
    async getAllProductivityLogs(): Promise<Array<[Date_, ProductivityLog]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProductivityLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProductivityLogs();
            return result;
        }
    }
    async getAllRevisionTopics(): Promise<Array<RevisionTopic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRevisionTopics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRevisionTopics();
            return result;
        }
    }
    async getCalendarEvent(arg0: Id): Promise<CalendarEvent> {
        if (this.processError) {
            try {
                const result = await this.actor.getCalendarEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCalendarEvent(arg0);
            return result;
        }
    }
    async getHabitCompletionDates(arg0: Id): Promise<Array<Date_>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHabitCompletionDates(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHabitCompletionDates(arg0);
            return result;
        }
    }
    async getProductivityLog(arg0: Date_): Promise<ProductivityLog> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductivityLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductivityLog(arg0);
            return result;
        }
    }
    async saveProductivityLog(arg0: Date_, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProductivityLog(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProductivityLog(arg0, arg1, arg2);
            return result;
        }
    }
    async updateCalendarEvent(arg0: Id, arg1: string, arg2: Date_, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCalendarEvent(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCalendarEvent(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
